### PR TITLE
C16

### PR DESCRIPTION
**Pull request by gyurco**
- New read/write 1541 from Dar
- Parametrized PAL/NTSC build, the clock multiplexer prevents Quartus to optimize the timing, also the compile time is 3x less now.

### CODE REVIEW

**Comment by harbaum** [comment]
Wow. I'll test that asap. I once tried to port the write enabled 1541 but failed miserably ....

**Comment by gyurco** [comment]
I didn't try writing myself, if it doesn't work, I'll educate myself a bit with the 1541 DOS and will go fix it.

**Comment by gyurco** [comment]
Well, a simple SAVE "xxx",8 worked for me with a one-line Basic program.

**Comment by harbaum** [comment]
Yes, indeed, it's working. Excellent!

I just gave you access to the repositories. Please feel invited to release a binary for this. I could do that myself. But honor to whom honor is due ...

**Comment by harbaum** [comment]
The fast loader in Zador doesn't work. Actually i don't remember if it ever worked before. But that might be an indication that the 1541 vs. c61 CPU speeds don't match perfectly. But that's only a minor issue.

I am seriously impressed by this version.

**Comment by gyurco** [comment]
I also found some disks which just hang, but simply using clk32 as the disk clock doesn't fix them. Will do further debugging, hopefully I'll find something.

**Comment by harbaum** [comment]
Indeed, most of the Bauknecht disks don't load. I am pretty sure some of them worked in the past.

**Comment by gyurco** [comment]
So I think I found out the issue - and you already fixed it :) But that fix was lost with the update.
But then decided to update a bit more - now that new game, Pet Rescue loads, too.
https://github.com/mist-devel/mist-board/pull/58

If you can test it, and give your blessing on it, I'll do an "official" binary release.

**Comment by sorgelig** [comment]
May be i have different copy of Pet Rescue, but it doesn't load the game itself. C1541 eventually hangs after short time of loading with LED on. C16 stays on "Preparing Worlds." screen.

**Comment by sorgelig** [comment]
Further lowering down the counter size to 31 fixes this game.

**Comment by harbaum** [comment]
Slipstream now loads and so does the young gen demo. But neither MOS nor the fast loader of Zador work for me. IMHO both CPUs are not cycle exact so this may actually be related to the fact that two different implementations try to do synchronous communication here.

**Comment by gyurco** [comment]
It's easy to switch to a common CPU, I'll test with it. Also the IEC communication crosses clock boundaries, maybe needs a synchronizer.

**Comment by harbaum** [comment]
As suggested by @sorgelig i reduced the 1541 clock another little bit and that indeed makes MOS, slipstream, Zador fastloader and Younggen all load nicely :-)

**Comment by harbaum** [comment]
I was too fast. younggen works with 31 but not with 30 while zador and MOS work with 30 but not with 31 ... grumble ...

**Comment by harbaum** [comment]
Anyway. Please feel free to release this. We can still release updates later.

**Comment by gyurco** [comment]
I can work on it later on anyway...but where can I find this Younggen demo, searching for it is not successful.

**Comment by harbaum** [comment]
This seems to be it:
https://plus4world.powweb.com/software/TYG_Demo

**Pull request merged**
