### PR TITLE
15 kHZ mode for sms via scandoubler_disable option and scanlines option.

### PR DESCRIPTION
**Pull request by phoboz**
Enabled 15 kHz mode and scanlines option for Sega Master System core.
The 15 kHz mode is selected using the mist.ini file via 'scandoubler_disable=1'
However the osd rolls in 15 kHz mode, but the VGA mode works just as before.

### CODE REVIEW

**Comment by harbaum** [comment]
Thanks! I'll have a look at the rolling ...

**Comment by robinsonb5** [comment]
Are you generating composite sync for 15KHz mode?  The OSD module can't cope with composite sync, so you'll need to feed the unmerged H and V sync signals into the OSD.

**Comment by phoboz** [comment]
No, I have separate HSync and VSync signals. The same 15 kHz signal is fed into the scandoubler in VGA mode, and the osd works well (no rolling) in VGA mode. The scandoubler module is from the soc tutorial lesson11, and I assume it generates new sync signals for VGA, which is then fed to the osd. So maybe there is a small problem with the separation of the sync signals that the tv and the scandoubler can cope with, but not the osd? The composite sync in 15 kHz mode is derived from the separate signals as:
CSync = not (HSync xor VSync)

**Comment by phoboz** [comment]
I did some reading on PAL and NTSC sync signals. So I need to work a little bit more on properly separating the sync signals during the vertical blank period, as there is some special handling during that time. When the sync signals got merged again for composite sync to the TV, the combined signal was correct, but maybe the osd got confused with the incorrect separation? E.g. the osd get some hsync pulses on the vsync line during the vertical blanking period. I don't know how sensitive the osd is in the vertical blanking period, but it might interpret these shorter pulses as a vertical sync, which might explain the rolling. Interesting that it worked when feed trough the scandoubler, which latches the sync pulses at double clockrate...

PS. I consider this work a learning phase as I really want to port fpgagen Genesis/Megadrive core to the MiST. I understand that the 128 kByte video memory is the problem, but I have ordered an DE1 board to start ftom that direction. E.g. it will need an multiport sdram controller running at 128 MHz according to Gregory  (something similar to what the FPGAPCE core has) Another option would be to go from the Master System core towards the Megadrive, as the Megadrive also runs SMS games. All of these systems VDPs are an evoultion of the MSX->Master System->Megadrive VDPs, but in the latest case the vram is to large for the fpga.

**Comment by phoboz** [comment]
Now the osd is working in 15 kHz mode as well. I have revised the separation of composite sync into separate vertical and horizontal sync signals. Tested both NTSC and PAL video modes, both with 'scandoubler_disable=1' and 'scandoubler_disable=0' In all 4 cases the osd is stable.

**Comment by harbaum** [comment]
"fpgagen Genesis/Megadrive"

I am very VERY interested in that and will lend a helping hand in that. And yes, this is exacly the problem. And yes, we need to add a second interface to the SDRAM controller.

**Comment by renaudhelias** [comment]
https://github.com/renaudhelias/CoreAmstrad/blob/master/BuildYourOwnZ80Computer/zsdram.v
sdram.v with : din/dout/addr/oe/we and zram_dout/zram_addr/zram_oe interface.
The zram_oe is used to insert some operation_wait in RAM while you are out of screen (not(DISP)), for a better stability of RAM.

**Pull request merged**
